export type ListaMaterial = {
  id_estoque: number,
  id_conv_prod: number,
  id_conv: number,
  id_produto: number,
  descricao: string,
  unidade: string,
  grupo: string,
  data: Date,
  data_dev: Date,
  quantidade: number,
  valor: number,
  descontos: number,
  total: number,
  hora: Date,
  cortesia: string,
  retornavel: string,
  status: string,

}