export const listacheckida = [

  // Parâmetros 
  { id_check: 1, descricao: "Cadeiras", status: false, tipo: "parametros" },
  { id_check: 2, descricao: "Câmara Ardente", status: false, tipo: "parametros" },
  { id_check: 3, descricao: "Tapete", status: false, tipo: "parametros" },
  { id_check: 4, descricao: "Velas", status: false, tipo: "parametros" },
  { id_check: 5, descricao: "Livro de Presença", status: false, tipo: "parametros" },
  { id_check: 6, descricao: "Tenda", status: false, tipo: "parametros" },
  { id_check: 7, descricao: "Extensão", status: false, tipo: "parametros" },
  { id_check: 8, descricao: "Lâmpada", status: false, tipo: "parametros" },
  { id_check: 9, descricao: "Jogo de Cortina", status: false, tipo: "parametros" },

  // Mantimentos
  { id_check: 10, descricao: "03 Copo 150 ml", status: false, tipo: "mantimentos" },
  { id_check: 11, descricao: "04 Copos 50 ml", status: false, tipo: "mantimentos" },
  { id_check: 12, descricao: "03 Café", status: false, tipo: "mantimentos" },
  { id_check: 13, descricao: "03 Açúcar", status: false, tipo: "mantimentos" },
  { id_check: 14, descricao: "01 Bolacha Salgada", status: false, tipo: "mantimentos" },
  { id_check: 15, descricao: "01 Amido de Milho", status: false, tipo: "mantimentos" },
  { id_check: 16, descricao: "01 kg de Arroz", status: false, tipo: "mantimentos" },
  { id_check: 17, descricao: "01 Caldo de Carne", status: false, tipo: "mantimentos" },
  { id_check: 18, descricao: "01 Pacote de Colher Desc", status: false, tipo: "mantimentos" },
  { id_check: 19, descricao: "05 Sacos p/Lixeiro", status: false, tipo: "mantimentos" },
  { id_check: 20, descricao: "01 Macarrão", status: false, tipo: "mantimentos" },
  { id_check: 21, descricao: "01 Coloral", status: false, tipo: "mantimentos" },
  { id_check: 22, descricao: "06 Pacote de Ervas", status: false, tipo: "mantimentos" },
  { id_check: 23, descricao: "01 Alho", status: false, tipo: "mantimentos" },
  { id_check: 24, descricao: "03 Cenouras", status: false, tipo: "mantimentos" },
  { id_check: 25, descricao: "03 Batatinha e Tomate", status: false, tipo: "mantimentos" },
  { id_check: 26, descricao: "02 Carne Moída Gostosinha", status: false, tipo: "mantimentos" },
  { id_check: 27, descricao: "01 Kit Almoço: 1 Frango – 3 Batatinha – 3 Tomate – 3 Cenoura - 1 Alho – 1 Pimentão – 1 Cheiro Verde", status: false, tipo: "mantimentos" },

  // Itens
  { id_check: 28, descricao: "02 Garrafas Chá/Café", status: false, tipo: "itens" },
  { id_check: 29, descricao: "01 Aferidor de Pressão", status: false, tipo: "itens" },
  { id_check: 30, descricao: "01 Garrafão d’Água", status: false, tipo: "itens" },
  { id_check: 31, descricao: "01 Gelágua", status: false, tipo: "itens" },
  { id_check: 32, descricao: "01 Caixa Organizadora", status: false, tipo: "itens" },
  { id_check: 33, descricao: "01 Caldeirão com Tampa", status: false, tipo: "itens" },
  { id_check: 34, descricao: "02 Canecas Café/Chá", status: false, tipo: "itens" },
  { id_check: 35, descricao: "02 Bandeja Plástica", status: false, tipo: "itens" },
  { id_check: 36, descricao: "01 Peneira", status: false, tipo: "itens" },
  { id_check: 37, descricao: "01 Faca", status: false, tipo: "itens" },
  { id_check: 38, descricao: "02 Coadores", status: false, tipo: "itens" },
  { id_check: 39, descricao: "01 Flanela", status: false, tipo: "itens" },
  { id_check: 40, descricao: "01 Colher e 01 Concha", status: false, tipo: "itens" },
  { id_check: 41, descricao: "01 Maleta de 1º Socorros", status: false, tipo: "itens" },
  { id_check: 42, descricao: "10 Toucas Descartáveis", status: false, tipo: "itens" },
  { id_check: 43, descricao: "02 Guardanapos", status: false, tipo: "itens" },


];

export const listacheckvolta = [
  // Parâmetros 
  { id_check: 1, descricao: "Cadeiras", status: false, tipo: "parametros" },
  { id_check: 2, descricao: "Câmara Ardente", status: false, tipo: "parametros" },
  { id_check: 3, descricao: "Tapete", status: false, tipo: "parametros" },
  { id_check: 4, descricao: "Velas", status: false, tipo: "parametros" },
  { id_check: 5, descricao: "Livro de Presença", status: false, tipo: "parametros" },
  { id_check: 6, descricao: "Tenda", status: false, tipo: "parametros" },
  { id_check: 7, descricao: "Extensão", status: false, tipo: "parametros" },
  { id_check: 8, descricao: "Lâmpada", status: false, tipo: "parametros" },
  { id_check: 9, descricao: "Jogo de Cortina", status: false, tipo: "parametros" },

  // Mantimentos
  { id_check: 10, descricao: "03 Copo 150 ml", status: false, tipo: "mantimentos" },
  { id_check: 11, descricao: "04 Copos 50 ml", status: false, tipo: "mantimentos" },
  { id_check: 12, descricao: "03 Café", status: false, tipo: "mantimentos" },
  { id_check: 13, descricao: "03 Açúcar", status: false, tipo: "mantimentos" },
  { id_check: 14, descricao: "01 Bolacha Salgada", status: false, tipo: "mantimentos" },
  { id_check: 15, descricao: "01 Amido de Milho", status: false, tipo: "mantimentos" },
  { id_check: 16, descricao: "01 kg de Arroz", status: false, tipo: "mantimentos" },
  { id_check: 17, descricao: "01 Caldo de Carne", status: false, tipo: "mantimentos" },
  { id_check: 18, descricao: "01 Pacote de Colher Desc", status: false, tipo: "mantimentos" },
  { id_check: 19, descricao: "05 Sacos p/Lixeiro", status: false, tipo: "mantimentos" },
  { id_check: 20, descricao: "01 Macarrão", status: false, tipo: "mantimentos" },
  { id_check: 21, descricao: "01 Coloral", status: false, tipo: "mantimentos" },
  { id_check: 22, descricao: "06 Pacote de Ervas", status: false, tipo: "mantimentos" },
  { id_check: 23, descricao: "01 Alho", status: false, tipo: "mantimentos" },
  { id_check: 24, descricao: "03 Cenouras", status: false, tipo: "mantimentos" },
  { id_check: 25, descricao: "03 Batatinha e Tomate", status: false, tipo: "mantimentos" },
  { id_check: 26, descricao: "02 Carne Moída Gostosinha", status: false, tipo: "mantimentos" },
  { id_check: 27, descricao: "01 Kit Almoço: 1 Frango – 3 Batatinha – 3 Tomate – 3 Cenoura - 1 Alho – 1 Pimentão – 1 Cheiro Verde", status: false, tipo: "mantimentos" },

  // Itens
  { id_check: 28, descricao: "02 Garrafas Chá/Café", status: false, tipo: "itens" },
  { id_check: 29, descricao: "01 Aferidor de Pressão", status: false, tipo: "itens" },
  { id_check: 30, descricao: "01 Garrafão d’Água", status: false, tipo: "itens" },
  { id_check: 31, descricao: "01 Gelágua", status: false, tipo: "itens" },
  { id_check: 32, descricao: "01 Caixa Organizadora", status: false, tipo: "itens" },
  { id_check: 33, descricao: "01 Caldeirão com Tampa", status: false, tipo: "itens" },
  { id_check: 34, descricao: "02 Canecas Café/Chá", status: false, tipo: "itens" },
  { id_check: 35, descricao: "02 Bandeja Plástica", status: false, tipo: "itens" },
  { id_check: 36, descricao: "01 Peneira", status: false, tipo: "itens" },
  { id_check: 37, descricao: "01 Faca", status: false, tipo: "itens" },
  { id_check: 38, descricao: "02 Coadores", status: false, tipo: "itens" },
  { id_check: 39, descricao: "01 Flanela", status: false, tipo: "itens" },
  { id_check: 40, descricao: "01 Colher e 01 Concha", status: false, tipo: "itens" },
  { id_check: 41, descricao: "01 Maleta de 1º Socorros", status: false, tipo: "itens" },
  { id_check: 42, descricao: "10 Toucas Descartáveis", status: false, tipo: "itens" },
  { id_check: 43, descricao: "02 Guardanapos", status: false, tipo: "itens" },
];